/**
 * report.js — Prism PDF Report renderer
 * Loaded by report.html (external file required by MV3 CSP: script-src 'self').
 * Reads { prismReport } from chrome.storage.local, renders, auto-opens print.
 */

// ── Helpers ──────────────────────────────────────────────────────────────────
function esc(str) {
  return String(str || '')
    .replace(/&/g, '&amp;')
    .replace(/</g,  '&lt;')
    .replace(/>/g,  '&gt;')
    .replace(/"/g,  '&quot;')
    .replace(/'/g,  '&#039;');
}

function domain(url) {
  try { return new URL(url).hostname.replace(/^www\./, ''); }
  catch { return url || ''; }
}

function scoreColor(s) {
  if (s >= 70) return '#3471CE';
  if (s >= 40) return '#7B6EF6';
  return '#8B1A2F';
}

function scoreLabel(s) {
  if (s >= 70) return 'Verified';
  if (s >= 40) return 'Contested';
  return 'Disputed';
}

function formatDate(iso) {
  try {
    return new Date(iso).toLocaleString(undefined, {
      year: 'numeric', month: 'long', day: 'numeric',
      hour: '2-digit', minute: '2-digit',
    });
  } catch { return iso; }
}

function renderSourceItem(s, stance) {
  const cls = stance.toLowerCase();
  return `
    <li class="source-item">
      <div class="source-meta-row">
        <span class="source-badge ${esc(cls)}">${esc(stance)}</span>
        <span class="source-domain">${esc(domain(s.url))}</span>
      </div>
      <p class="source-title">${esc(s.title || 'Untitled source')}</p>
    </li>`;
}

// ── Render ────────────────────────────────────────────────────────────────────
function renderReport(data) {
  const r     = data.analysisResult;
  const score = Math.max(0, Math.min(100, Math.round(r.verifiability_score || 0)));
  const color = scoreColor(score);
  const label = scoreLabel(score);
  const date  = formatDate(data.analyzedAt);

  // New schema: unified sources array with Claude-assigned labels.
  // Legacy fallback: verification_sources / counter_sources (old reports in storage).
  let sourcesHtml = '';
  if (r.sources && r.sources.length) {
    sourcesHtml = r.sources
      .map(s => renderSourceItem(s, s.label || s.stance || 'Neutral'))
      .join('');
  } else {
    const supportive = (r.verification_sources || []).map(s => renderSourceItem(s, 'Supportive')).join('');
    const opposing   = (r.counter_sources      || []).map(s => renderSourceItem(s, 'Opposing')).join('');
    sourcesHtml = supportive + opposing;
  }
  const allSources = sourcesHtml;

  let counterSection = '';
  if (data.challengeResult) {
    const cr       = data.challengeResult;
    const cSummary = cr.summary ? `<p class="counter-summary">${esc(cr.summary)}</p>` : '';
    const cSources = (cr.sources || []).map(s => renderSourceItem(s, 'Reasoning')).join('');
    counterSection = `
      <div class="section">
        <div class="section-label">Counterargument</div>
        ${cSummary}
        ${cSources ? `<ul class="sources-list" style="margin-top:14px">${cSources}</ul>` : ''}
      </div>`;
  }

  document.getElementById('report').innerHTML = `
    <div class="report-header">
      <span class="report-brand">Prism</span>
      <div class="report-meta">
        <div>Analysis Report</div>
        <div>${esc(date)}</div>
      </div>
    </div>

    <div class="section">
      <div class="section-label">Analyzed Article</div>
      <p class="article-title">${esc(data.pageTitle || 'Untitled')}</p>
      <a class="article-url" href="${esc(data.pageUrl)}" target="_blank" rel="noopener noreferrer">
        ${esc(data.pageUrl)}
      </a>
    </div>

    <div class="section">
      <div class="section-label">Verifiability</div>
      <div class="score-row">
        <span class="score-number" style="color:${color}">${score}</span>
        <div class="score-right">
          <span class="score-denom">/100</span>
          <span class="score-label" style="color:${color}">${label}</span>
        </div>
      </div>
      <div class="score-track">
        <div class="score-fill" style="width:${score}%; background:${color}"></div>
      </div>
      <p class="score-desc">${esc(r.verifiability_description || '')}</p>
    </div>

    <div class="section">
      <div class="section-label">Summary</div>
      <p class="summary-body">${esc(r.summary || '')}</p>
    </div>

    ${allSources ? `
    <div class="section">
      <div class="section-label">Sources</div>
      <ul class="sources-list">${allSources}</ul>
    </div>` : ''}

    ${counterSection}

    <div class="report-footer">
      <span>Generated by Prism</span>
      <span>${esc(date)}</span>
    </div>
  `;

  document.title = `Prism — ${data.pageTitle || 'Analysis Report'}`;
}

// ── Load ──────────────────────────────────────────────────────────────────────
chrome.storage.local.get('prismReport', ({ prismReport }) => {
  if (!prismReport || !prismReport.analysisResult) {
    document.getElementById('loading-state').classList.add('hidden');
    document.getElementById('report').innerHTML =
      '<p style="padding:32px;color:#8B1A2F;">No report data found. Run an analysis first.</p>';
    return;
  }
  document.getElementById('loading-state').classList.add('hidden');
  document.getElementById('print-bar-wrap').classList.remove('hidden');
  document.getElementById('report').classList.remove('hidden');
  document.getElementById('print-btn').addEventListener('click', () => window.print());
  renderReport(prismReport);
});
